In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm

In [3]:
data = pd.read_excel("default of credit card clients.xls", engine = "xlrd")
data

Unnamed: 0         X1   X2         X3        X4   X5     X6     X7  \
0             ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2   
1              1      20000    2          2         1   24      2      2   
2              2     120000    2          2         2   26     -1      2   
3              3      90000    2          2         2   34      0      0   
4              4      50000    2          2         1   37      0      0   
...          ...        ...  ...        ...       ...  ...    ...    ...   
29996      29996     220000    1          3         1   39      0      0   
29997      29997     150000    1          3         2   43     -1     -1   
29998      29998      30000    1          2         2   37      4      3   
29999      29999      80000    1          3         1   41      1     -1   
30000      30000      50000    1          2         1   46      0      0   

          X8     X9  ...        X15        X16        X17       X18       X19  \
0      PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2   
1         -1     -1  ...          0          0          0         0       689   
2          0      0  ...       3272       3455       3261         0      1000   
3          0      0  ...      14331      14948      15549      1518      1500   
4          0      0  ...      28314      28959      29547      2000      2019   
...      ...    ...  ...        ...        ...        ...       ...       ...   
29996      0      0  ...      88004      31237      15980      8500     20000   
29997     -1     -1  ...       8979       5190          0      1837      3526   
29998      2     -1  ...      20878      20582      19357         0         0   
29999      0      0  ...      52774      11855      48944     85900      3409   
30000      0      0  ...      36535      32428      15313      2078      1800   

            X20       X21       X22       X23                           Y  
0      PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
1             0         0         0         0                           1  
2          1000      1000         0      2000                           1  
3          1000      1000      1000      5000                           0  
4          1200      1100      1069      1000                           0  
...         ...       ...       ...       ...                         ...  
29996      5003      3047      5000      1000                           0  
29997      8998       129         0         0                           0  
29998     22000      4200      2000      3100                           1  
29999      1178      1926     52964      1804                           1  
30000      1430      1000      1000      1000                           1  

[30001 rows x 25 columns]

In [4]:
df = data.drop(index = 0)
df

Unnamed: 0      X1 X2 X3 X4  X5  X6  X7  X8  X9  ...    X15    X16  \
1              1   20000  2  2  1  24   2   2  -1  -1  ...      0      0   
2              2  120000  2  2  2  26  -1   2   0   0  ...   3272   3455   
3              3   90000  2  2  2  34   0   0   0   0  ...  14331  14948   
4              4   50000  2  2  1  37   0   0   0   0  ...  28314  28959   
5              5   50000  1  2  1  57  -1   0  -1   0  ...  20940  19146   
...          ...     ... .. .. ..  ..  ..  ..  ..  ..  ...    ...    ...   
29996      29996  220000  1  3  1  39   0   0   0   0  ...  88004  31237   
29997      29997  150000  1  3  2  43  -1  -1  -1  -1  ...   8979   5190   
29998      29998   30000  1  2  2  37   4   3   2  -1  ...  20878  20582   
29999      29999   80000  1  3  1  41   1  -1   0   0  ...  52774  11855   
30000      30000   50000  1  2  1  46   0   0   0   0  ...  36535  32428   

         X17    X18    X19    X20   X21    X22   X23  Y  
1          0      0    689      0     0      0     0  1  
2       3261      0   1000   1000  1000      0  2000  1  
3      15549   1518   1500   1000  1000   1000  5000  0  
4      29547   2000   2019   1200  1100   1069  1000  0  
5      19131   2000  36681  10000  9000    689   679  0  
...      ...    ...    ...    ...   ...    ...   ... ..  
29996  15980   8500  20000   5003  3047   5000  1000  0  
29997      0   1837   3526   8998   129      0     0  0  
29998  19357      0      0  22000  4200   2000  3100  1  
29999  48944  85900   3409   1178  1926  52964  1804  1  
30000  15313   2078   1800   1430  1000   1000  1000  1  

[30000 rows x 25 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 1 to 30000
Data columns (total 25 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  30000 non-null  object
 1   X1          30000 non-null  object
 2   X2          30000 non-null  object
 3   X3          30000 non-null  object
 4   X4          30000 non-null  object
 5   X5          30000 non-null  object
 6   X6          30000 non-null  object
 7   X7          30000 non-null  object
 8   X8          30000 non-null  object
 9   X9          30000 non-null  object
 10  X10         30000 non-null  object
 11  X11         30000 non-null  object
 12  X12         30000 non-null  object
 13  X13         30000 non-null  object
 14  X14         30000 non-null  object
 15  X15         30000 non-null  object
 16  X16         30000 non-null  object
 17  X17         30000 non-null  object
 18  X18         30000 non-null  object
 19  X19         30000 non-null  object
 20  X20   

In [6]:
df.isnull().sum()

Unnamed: 0    0
X1            0
X2            0
X3            0
X4            0
X5            0
X6            0
X7            0
X8            0
X9            0
X10           0
X11           0
X12           0
X13           0
X14           0
X15           0
X16           0
X17           0
X18           0
X19           0
X20           0
X21           0
X22           0
X23           0
Y             0
dtype: int64

In [7]:
df.describe()

Unnamed: 0     X1     X2     X3     X4     X5     X6     X7     X8  \
count        30000  30000  30000  30000  30000  30000  30000  30000  30000   
unique       30000     81      2      7      4     56     11     11     11   
top          30000  50000      2      2      2     29      0      0      0   
freq             1   3365  18112  14030  15964   1605  14737  15730  15764   

           X9  ...    X15    X16    X17    X18    X19    X20    X21    X22  \
count   30000  ...  30000  30000  30000  30000  30000  30000  30000  30000   
unique     11  ...  21548  21010  20604   7943   7899   7518   6937   6897   
top         0  ...      0      0      0      0      0      0      0      0   
freq    16455  ...   3195   3506   4020   5249   5396   5968   6408   6703   

          X23      Y  
count   30000  30000  
unique   6939      2  
top         0      0  
freq     7173  23364  

[4 rows x 25 columns]

In [8]:
df.dropna()

Unnamed: 0      X1 X2 X3 X4  X5  X6  X7  X8  X9  ...    X15    X16  \
1              1   20000  2  2  1  24   2   2  -1  -1  ...      0      0   
2              2  120000  2  2  2  26  -1   2   0   0  ...   3272   3455   
3              3   90000  2  2  2  34   0   0   0   0  ...  14331  14948   
4              4   50000  2  2  1  37   0   0   0   0  ...  28314  28959   
5              5   50000  1  2  1  57  -1   0  -1   0  ...  20940  19146   
...          ...     ... .. .. ..  ..  ..  ..  ..  ..  ...    ...    ...   
29996      29996  220000  1  3  1  39   0   0   0   0  ...  88004  31237   
29997      29997  150000  1  3  2  43  -1  -1  -1  -1  ...   8979   5190   
29998      29998   30000  1  2  2  37   4   3   2  -1  ...  20878  20582   
29999      29999   80000  1  3  1  41   1  -1   0   0  ...  52774  11855   
30000      30000   50000  1  2  1  46   0   0   0   0  ...  36535  32428   

         X17    X18    X19    X20   X21    X22   X23  Y  
1          0      0    689      0     0      0     0  1  
2       3261      0   1000   1000  1000      0  2000  1  
3      15549   1518   1500   1000  1000   1000  5000  0  
4      29547   2000   2019   1200  1100   1069  1000  0  
5      19131   2000  36681  10000  9000    689   679  0  
...      ...    ...    ...    ...   ...    ...   ... ..  
29996  15980   8500  20000   5003  3047   5000  1000  0  
29997      0   1837   3526   8998   129      0     0  0  
29998  19357      0      0  22000  4200   2000  3100  1  
29999  48944  85900   3409   1178  1926  52964  1804  1  
30000  15313   2078   1800   1430  1000   1000  1000  1  

[30000 rows x 25 columns]

In [9]:
x = df.drop(columns   = ['Y'], axis = 1)
y = df['Y']

In [10]:
x

Unnamed: 0      X1 X2 X3 X4  X5  X6  X7  X8  X9  ...     X14    X15  \
1              1   20000  2  2  1  24   2   2  -1  -1  ...     689      0   
2              2  120000  2  2  2  26  -1   2   0   0  ...    2682   3272   
3              3   90000  2  2  2  34   0   0   0   0  ...   13559  14331   
4              4   50000  2  2  1  37   0   0   0   0  ...   49291  28314   
5              5   50000  1  2  1  57  -1   0  -1   0  ...   35835  20940   
...          ...     ... .. .. ..  ..  ..  ..  ..  ..  ...     ...    ...   
29996      29996  220000  1  3  1  39   0   0   0   0  ...  208365  88004   
29997      29997  150000  1  3  2  43  -1  -1  -1  -1  ...    3502   8979   
29998      29998   30000  1  2  2  37   4   3   2  -1  ...    2758  20878   
29999      29999   80000  1  3  1  41   1  -1   0   0  ...   76304  52774   
30000      30000   50000  1  2  1  46   0   0   0   0  ...   49764  36535   

         X16    X17    X18    X19    X20   X21    X22   X23  
1          0      0      0    689      0     0      0     0  
2       3455   3261      0   1000   1000  1000      0  2000  
3      14948  15549   1518   1500   1000  1000   1000  5000  
4      28959  29547   2000   2019   1200  1100   1069  1000  
5      19146  19131   2000  36681  10000  9000    689   679  
...      ...    ...    ...    ...    ...   ...    ...   ...  
29996  31237  15980   8500  20000   5003  3047   5000  1000  
29997   5190      0   1837   3526   8998   129      0     0  
29998  20582  19357      0      0  22000  4200   2000  3100  
29999  11855  48944  85900   3409   1178  1926  52964  1804  
30000  32428  15313   2078   1800   1430  1000   1000  1000  

[30000 rows x 24 columns]

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 2)
y_train

19283    0
1714     0
15938    0
700      0
29599    1
        ..
18899    1
11799    0
6638     0
2576     0
23721    0
Name: Y, Length: 24000, dtype: object

In [24]:
print(y_train.dtype)  # Should be int, not float or object
print(type(y_train))  # Should be a pandas Series or NumPy array



int64
<class 'numpy.ndarray'>


In [23]:
import numpy as np
y_train = np.array(y_train, dtype=int)  # Ensures integer labels


In [26]:
print(y_test.dtype)  # Should be int, not float or object
print(type(y_test))  # Should be a pandas Series or NumPy array


int64
<class 'numpy.ndarray'>


In [25]:
import numpy as np
y_test = np.array(y_test, dtype=int)  # Ensures integer labels


In [14]:
scaler = StandardScaler()
scaler.fit(x_train)



StandardScaler()

In [15]:
x_train = scaler.fit_transform(x_train)

x_test = scaler.transform(x_test)
print(x_train)

[[ 0.49115483  0.48069546  0.80977982 ... -0.07012854 -0.15230166
   0.27375482]
 [-1.53378791  1.71593352  0.80977982 ...  0.00749145  0.08503608
  -0.0081909 ]
 [ 0.10562159 -0.90894735  0.80977982 ... -0.11856341 -0.32078508
  -0.30280504]
 ...
 [-0.96626454  3.41438584 -1.23490358 ... -0.17879652 -0.20810207
  -0.2144208 ]
 [-1.43443674  0.09468357 -1.23490358 ...  0.13168342  0.15267294
   0.10965475]
 [ 1.0026635   0.78950498  0.80977982 ... -0.25157301 -0.23617137
  -0.16922699]]


In [16]:
model = svm.SVC(kernel='linear')

In [17]:
model.fit(x_train, y_train)

SVC(kernel='linear')

In [19]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(y_train, x_train_prediction)
print("Accuracy score: ", training_data_accuracy*100 )
print(x_train_prediction)

Accuracy score:  80.92083333333333
[0 0 0 ... 0 0 0]


In [20]:
conf_matrix = confusion_matrix(y_train, x_train_prediction)
classification = classification_report(y_train, x_train_prediction)
print("confusion_matrix: \n", conf_matrix)
print("Accuracy score of svm model is: ",training_data_accuracy)
print("classification_report: \n", classification)

confusion_matrix: 
 [[18209   490]
 [ 4089  1212]]
Accuracy score of svm model is:  0.8092083333333333
classification_report: 
               precision    recall  f1-score   support

           0       0.82      0.97      0.89     18699
           1       0.71      0.23      0.35      5301

    accuracy                           0.81     24000
   macro avg       0.76      0.60      0.62     24000
weighted avg       0.79      0.81      0.77     24000



In [27]:
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(y_test, x_test_prediction)
print("Accuracy score: ", test_data_accuracy*100 )
print(x_test_prediction)

Accuracy score:  80.85
[0 0 0 ... 0 0 0]


In [28]:
conf_matrix = confusion_matrix(y_test, x_test_prediction)
classification = classification_report(y_test, x_test_prediction)
print("confusion_matrix: \n", conf_matrix)
print("Accuracy score of svm model is: ",test_data_accuracy)
print("classification_report: \n", classification)

confusion_matrix: 
 [[4518  147]
 [1002  333]]
Accuracy score of svm model is:  0.8085
classification_report: 
               precision    recall  f1-score   support

           0       0.82      0.97      0.89      4665
           1       0.69      0.25      0.37      1335

    accuracy                           0.81      6000
   macro avg       0.76      0.61      0.63      6000
weighted avg       0.79      0.81      0.77      6000



In [32]:
new_data = np.array([1	,20000,	2,	2,	1	,24,	2	,2	,-1	,-1	,-2	,-2	,3913	,3102,	689	,0	,0,	0,	0	,689,	0	,0	,0	,0])
input_data_reshape = new_data.reshape(1,-1)
prediction = model.predict(input_data_reshape)
if prediction == 1:
    print(f"Prediciton:{prediction} The User is  Trustworthy!")
else:
    print(f"Prediction:{prediction} The User is not Trustworthy!")


Prediciton:[1] The User is  Trustworthy!


In [33]:
new_data = np.array([8,100000,2,2,2,23,0,-1,-1,0,0,-1,11876,380,601,221,-159,567,380,601,0,581,1687,1542])
input_data_reshape = new_data.reshape(1,-1)
prediction = model.predict(input_data_reshape)
if prediction == 1:
    print(f"Prediciton:{prediction} The User is  Trustworthy!")
else:
    print(f"Prediction:{prediction} The User is not Trustworthy!")


Prediction:[0] The User is not Trustworthy!


In [31]:
x_test.shape

(6000, 24)